[platformio]
src_dir = stator
include_dir = .
default_envs = stator, rotor

[env:stator]
platform = espressif32@7.0.1
board = esp32-s3-devkitc-1
framework = espidf
upload_speed = 921600
monitor_speed = 115200
build_flags = 
    -I stator/include
    -I shared/include
    -DCORE_DEBUG_LEVEL=3

[env:rotor]
platform = ststm32
board = bluepill_f103c8
framework = arduino
upload_speed = 115200
monitor_speed = 115200
build_src_filter = +<../rotor/src/>
build_flags = 
    -I rotor/include
    -I shared/include
    -DDEBUG_LEVEL=0
    -DCORE_DEBUG_LEVEL=3
